import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/Sidebar'
import Center from '../components/Center'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Purple Music</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black h-screen overflow-hidden">
        {/* <h1>Purple Music</h1>
        <h2>Your number one Purple music stream!</h2> */}
        <main className='flex'> 
          <Sidebar/>
          <Center/>
        </main>

        <div>{/* {Player} */}</div>
      </div>
    </>
  );
}
